// vue/diary/src/components/Login.vue
<script setup lang="ts">
import { signIn } from '@junobuild/core'

const login = async () => signIn()
</script>

<template>
  <div class="mt-10 flex items-center justify-center gap-x-6">
    <button
      type="button"
      @click="login"
      class="rounded-md bg-indigo-600 px-3.5 py-1.5 text-base font-semibold leading-7 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
    >
      <div class="flex items-center justify-center gap-1.5">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="currentColor"
          class="w-6 h-6"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9"
          />
        </svg>
        Sign In
      </div>
    </button>
  </div>
</template>

// react/poll/src/Login.js
import { NFIDProvider, signIn } from "@junobuild/core";
import { IconII } from "./IconII";
import { IconNFID } from "./IconNFID";

export const Login = () => {
  const signInNFID = () =>
    signIn({
      provider: new NFIDProvider({
        appName: "David presentation",
        logoUrl: "https://somewhere.com/your_logo.png",
      }),
    });

  return (
    <div className="mt-10 flex flex-col items-center justify-center gap-3 max-w-sm mx-auto">
      <button
        type="button"
        onClick={signIn}
        className="w-full rounded-md bg-black border-2 border-black hover:border-indigo-500 px-3.5 py-1.5 text-base font-semibold leading-7 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
      >
        <div className="flex items-center justify-center gap-1.5">
          <IconII />
          Continue with Internet Identity
        </div>
      </button>

      <button
        type="button"
        onClick={signInNFID}
        className="w-full rounded-md bg-white border-2 border-black hover:border-indigo-500 px-3.5 py-1.5 text-black hover:text-white font-semibold leading-7 shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
      >
        <div className="flex items-center justify-center gap-1.5">
          <IconNFID />
          Continue with NFID
        </div>
      </button>
    </div>
  );
};
