// rust/json/src/lib/components/Backdrop.svelte
<script lang="ts">
	export let spinner = false;
</script>

<div
	class:backdrop-blur-sm={spinner}
	class:backdrop-blur-xl={!spinner}
	class="fixed inset-0 z-40 bg-white/30 flex items-center justify-center"
>
	{#if spinner}
		<div
			class="w-12 h-12 rounded-full animate-spin border-[3px] border-solid border-lavender-blue-600 border-t-transparent"
		></div>
	{/if}
</div>

// rust/calls/src/components/Backdrop.tsx
import { FC } from "react";

interface BackdropProps {
  spinner?: boolean;
}

export const Backdrop: FC<BackdropProps> = (props) => {
  const { spinner = false } = props;

  return (
    <div
      className={`fixed inset-0 z-40 ${spinner ? "backdrop-blur-xs" : "backdrop-blur-xl"} flex items-center justify-center bg-white/30`}
    >
      {spinner && (
        <div className="border-lavender-blue-600 h-12 w-12 animate-spin rounded-full border-[3px] border-solid border-t-transparent"></div>
      )}
    </div>
  );
};
