// vue/diary/src/components/Auth.vue
<script setup lang="ts">
import {useAuthStore} from '../stores/auth.store';
import { storeToRefs } from 'pinia'
import Login from './Login.vue'
import Logout from './Logout.vue'

const store = useAuthStore()
const { user } = storeToRefs(store)
</script>

<template>
    <template v-if="user !== undefined && user !== null">
        <div>
            <slot />

            <Logout />
        </div>
    </template>

    <template v-else>
        <Login />
    </template>
</template>

// react/diary/src/Auth.js
import { useEffect, useState } from "react";
import { authSubscribe } from "@junobuild/core";
import { Login } from "./Login";
import { Logout } from "./Logout";

export const Auth = ({ children }) => {
  const [user, setUser] = useState(undefined);

  useEffect(() => {
    const sub = authSubscribe((user) => {
      setUser(user);
    });

    return () => sub();
  }, []);

  return (
    <>
      {user !== undefined && user !== null ? (
        <div>
          {children}

          <Logout />
        </div>
      ) : (
        <Login />
      )}
    </>
  );
};
