// rust/json/src/lib/components/Button.svelte
<script lang="ts">
	export let disabled: boolean | undefined = undefined;
</script>

<button
	on:click
	{disabled}
	class={`flex items-center gap-2 border-black dark:border-lavender-blue-500 border-[3px] transition-all rounded-sm py-1 px-8 my-2 font-semibold text-white bg-lavender-blue-500 dark:bg-black shadow-[5px_5px_0px_rgba(0,0,0,1)] dark:shadow-[5px_5px_0px_#7888ff] ${disabled === true ? 'opacity-25' : 'hover:bg-lavender-blue-600 dark:hover:bg-lavender-blue-300 dark:hover:text-black active:bg-lavender-blue-400 dark:active:bg-lavender-blue-500 active:shadow-none active:translate-x-[5px] active:translate-y-[5px]'}`}
>
	<slot />
</button>

// react/diary/src/Button.jsx
import PropTypes from "prop-types";

export const Button = ({ children, onClick, disabled = false }) => {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className={`flex items-center gap-2 border-black border-[3px] transition-all rounded-sm py-1 px-8 my-2 font-semibold text-white bg-lavender-blue-500 shadow-[5px_5px_0px_rgba(0,0,0,1)] ${disabled ? "opacity-25" : "hover:bg-lavender-blue-600 active:bg-lavender-blue-400 active:shadow-none active:translate-x-[5px] active:translate-y-[5px]"}`}
    >
      {children}
    </button>
  );
};

Button.propTypes = {
  children: PropTypes.node.isRequired,
  onClick: PropTypes.func.isRequired,
};
